### ISSUE TITLE
Some profile images on team page are not centered on mobile

### ISSUE THREAD

**Issue by FarfamaH** [AsperMISA/AsperMISA#12]

**Comment by Marshmallows7920** [comment]
looks like the problem is only on phones with screen sizes less than 500px

**Comment by Marshmallows7920** [comment]
problem was caused by margins in the staff2 class in the staff.scss file. removed them for now and it fixed the issue. We have to decide what we want more, the style of it being layed out or having everything centred in a small mobile screen size

**Comment by FarfamaH** [comment]
I readded the margins to staff2 but moved it to media query within it that only activates on desktop.
