### ISSUE TITLE
Hamburger menu on mobile has line through it when opening , scrolling, and closing.

### ISSUE THREAD

**Issue by AsperMISA** [AsperMISA/AsperMISA#35]
The issue is related to the bottom border going from red to white when you scroll. It can be traced to either main.js, navigation.scss (where the bottom border gets coloured), and/or navigation.html

**Comment by FarfamaH** [comment]
Fixed by removing

    nav a:hover {
    border-bottom: 5px solid white;  	
    }

from navigation.scss
